package exceptionCodes;

import java.io.FileNotFoundException;

import exceptionCodes.custom.TestingCustomException;

public class Main {
	public static void main(String[] args) {
//		{12,13,14,15}
		
		
//		System.out.println(5/0);
//		System.out.println(5+5);

//		try catch
//		throws
//		throw
//		custom exception
		
		// runtime exception vs compile time exception
		// exception hierarchy 
		
		
		
//		try {
//			System.out.println("hello");
//			System.out.println("World");
//			System.out.println(5/0);
//			System.out.println("After");
//
//		}
//		catch(Exception ate) {
//			System.out.println(ate.getClass());
//			System.out.println("arithmetic exception occured");
//		}
//		finally {
//			System.out.println("Finally");
//		}
		
//		existing exception - inherit;
//		constructor calling super method
//		object - throw
		
		TestingCustomException.display(17);
	}
}
